# -*- coding: utf-8 -*-
"""Con qué clase de «Mi seño particular» se refuerza cada tarjeta.

GENERADO por gen_seno_clases.py desde kydo/seno/ de ct3d. NO editar a mano.
Es una COPIA deliberada: este motor no puede importar `kydo.*` en ejecución
porque atiende también a Casatridimensional. Lo que la sostiene es
tests/test_seno_clases.py, que la rearma desde la fuente y falla si quedó vieja.

La clave es el GRADO y después la tarjeta: hay tarjetas reusadas en varios
grados y la seño sólo abre la clase del grado del cuaderno.
"""

# grado → {id de la tarjeta: (id del tema, título de la clase)}
CLASES = {
    1: {
        "abecedario": ("el-abecedario", "El abecedario"),
        "anterior_siguiente": ("cruzar-la-decena", "El número que sigue"),
        "armar_calculo_1": ("calculo-mental", "Sumar diez de memoria"),
        "armar_palabra": ("armar-palabras", "Armar palabras"),
        "calendario_1": ("el-calendario", "El calendario"),
        "cuerpos_1": ("cuerpos", "Cuerpos"),
        "donde_esta_1": ("contar-hasta-cien", "Contar de diez en diez"),
        "figuras_1": ("figuras", "Figuras"),
        "kiosco_1": ("el-kiosco", "El kiosco"),
        "letra_inicial": ("letra-inicial", "Con qué letra empieza"),
        "mas_o_menos_1": ("restar-quitando", "Restar quitando"),
        "medir_clips_1": ("medir-con-cuadraditos", "Medir con cuadraditos"),
        "ordenar_numeros": ("cruzar-la-decena", "El número que sigue"),
        "parejas_diez_1": ("parejas-que-suman-diez", "Parejas que suman diez"),
        "silabas_1": ("cuantas-partes", "Cuántas partes tiene"),
        "suma_rapida": ("sumar-juntando", "Sumar juntando"),
    },
    2: {
        "adivina_figura": ("figuras-y-sus-lados", "Figuras y sus lados"),
        "calculo_redondo": ("numeros-redondos", "Números redondos"),
        "comparar_numeros": ("numeros-hasta-1000", "Números hasta 1.000"),
        "comprension_lectora": ("comprension-2", "Comprensión de textos cortos"),
        "contar_saltando": ("contar-de-2-5-10", "Contar de 2, de 5 y de 10"),
        "dobles_2": ("dobles-y-mitades", "Dobles y mitades"),
        "familia_palabras": ("familia-de-palabras", "Familia de palabras"),
        "forma_redondo": ("cuanto-falta-para-llegar", "Cuánto falta para llegar"),
        "medir_regla_2": ("medir-con-la-regla", "Medir con la regla"),
        "multiplicacion_concepto": ("suma-repetida", "Veces: la suma repetida"),
        "parejas_cien_2": ("parejas-que-suman-cien", "Parejas que suman cien"),
        "posiciones_2": ("unidades-decenas-y-centenas", "Unidades, decenas y centenas"),
        "que_cuenta_resuelve": ("restar-con-canje-2", "Restar con canje"),
        "reloj": ("el-reloj", "El reloj"),
        "reparto_2": ("repartir-en-partes-iguales-2", "Repartir en partes iguales"),
        "signos_2": ("la-mayuscula", "Dónde va la mayúscula"),
        "sinonimos_antonimos": ("sinonimos-antonimos", "Sinónimos y antónimos"),
        "sumas_redondas": ("sumar-con-canje", "Sumar con canje"),
        "sustantivos": ("sustantivos-2", "Sustantivos"),
        "tablas_contrarreloj": ("suma-repetida", "Veces: la suma repetida"),
        "valor_posicional": ("numeros-hasta-1000", "Números hasta 1.000"),
    },
    3: {
        "bandeja_huevos_3": ("organizaciones-rectangulares", "Filas y columnas"),
        "cajero_automatico": ("pagar-con-billetes-3", "Pagar con billetes"),
        "comparar_numeros": ("numeracion-hasta-mil", "Los números hasta 1.000"),
        "comprension_lectora": ("comprension-3", "Comprensión lectora"),
        "cuadricula_3": ("orientacion-en-cuadricula", "Ubicar con dos números"),
        "cuerpos_geometricos": ("cuerpos-geometricos-3", "Cuerpos geométricos"),
        "derivadas_3": ("diminutivos-y-aumentativos", "Más chico y más grande"),
        "dialogo_signos_3": ("signos-de-pregunta", "Los signos que abren"),
        "figuras_3": ("figuras-y-lados", "Las figuras y sus lados"),
        "medir_3": ("medidas-en-tercero", "Metros, kilos y litros"),
        "mil_mas_menos_3": ("cien-y-mil-mas-o-menos", "Cien y mil, más o menos"),
        "multi_partes_3": ("multiplicar-por-una-cifra-3", "Multiplicar por una cifra"),
        "orden_alfabetico": ("orden-alfabetico", "Orden alfabético"),
        "ortografia_3ro": ("ge-gue-guee", "La u que no se oye"),
        "parejas_mil_3": ("parejas-que-suman-mil", "Parejas que suman mil"),
        "partes_oracion": ("partes-de-la-oracion", "Partes de la oración"),
        "rayo_por_diez_3": ("multiplicar-por-diez", "Multiplicar por 10, 100 y 1.000"),
        "reloj": ("la-hora", "La hora"),
        "reparto_con_resto": ("repartir-en-partes-iguales", "Repartir en partes iguales"),
        "resta_columnas": ("resta-con-canje-3", "Resta con canje"),
        "silaba_tonica": ("silaba-tonica", "Sílaba tónica"),
        "suma_columnas": ("resta-con-canje-3", "Resta con canje"),
        "tabla_pitagorica": ("concepto-de-multiplicacion", "Qué es multiplicar"),
        "tiempos_verbales": ("tiempos-verbales", "Tiempos verbales"),
    },
    4: {
        "abstractos_concretos": ("sustantivos", "Sustantivos concretos y abstractos"),
        "acentuacion": ("acentuacion", "Acentuación"),
        "angulos": ("clasificar-angulos", "Clasificar ángulos"),
        "completar_entero": ("concepto-de-fraccion", "Qué es una fracción"),
        "comprension_lectora": ("comprension", "Comprensión lectora"),
        "conectores": ("conectores", "Conectores"),
        "cuenta_larga": ("division-larga", "División con resto"),
        "cuerpos_caras_4": ("cuerpos-geometricos", "Cuerpos geométricos"),
        "dialogo_raya": ("dialogo", "Puntuación del diálogo"),
        "dividir": ("division-por-una-cifra", "División por una cifra"),
        "duelo_decimales": ("comparar-decimales", "Comparar decimales"),
        "duelo_fracciones": ("comparar-fracciones", "Comparar fracciones"),
        "equivalencias_medida_4": ("equivalencias-de-medida", "Equivalencias de medida"),
        "fracciones_equivalentes": ("fracciones-equivalentes", "Fracciones equivalentes"),
        "historia_orden": ("narrativa", "Ordenar el relato"),
        "mejor_oferta": ("comparar-precios", "Comparar precios"),
        "multiplicar": ("multiplicar-por-dos-cifras", "Multiplicar por dos cifras"),
        "plurales_z": ("plurales", "Plurales"),
        "prefijos_sufijos": ("prefijos-y-sufijos", "Prefijos y sufijos"),
        "problemas_mult_div": ("problemas-de-multiplicar-y-dividir", "Problemas de multiplicar y dividir"),
        "recta_numerica": ("recta-numerica", "Ubicar números en la recta"),
        "reparto_fracciones": ("fraccion-de-una-cantidad", "Fracción de una cantidad"),
        "resta_canje_4": ("resta-con-canje", "Resta con canje"),
        "serie": ("series-numericas", "Series numéricas"),
        "sopa": ("vocabulario", "Vocabulario"),
        "sujeto_predicado": ("sujeto-y-predicado", "Sujeto y predicado"),
        "suma_columnas": ("suma-en-columna", "Suma en columna"),
        "tablas_ninja": ("agilidad-con-las-tablas", "Agilidad con las tablas"),
        "triangulos_4": ("triangulos", "Triángulos: ¿se puede armar?"),
        "valor_posicional_4": ("valor-posicional", "Valor posicional hasta 100.000"),
    },
    5: {
        "analisis_sintactico": ("analisis-sintactico", "Núcleo del sujeto y del predicado"),
        "clases_palabra_5": ("los-adverbios", "La palabra que dice cómo"),
        "combinatoria_5": ("combinatoria", "Combinatoria"),
        "comprension_lectora": ("comprension-5", "Leer entre líneas"),
        "cuenta_escondida_5": ("las-partes-de-la-division", "Las partes de la división"),
        "cuenta_larga": ("division-con-resto-5", "División con resto"),
        "decimales_fraccion": ("decimales-y-fracciones", "Decimales y fracciones"),
        "dividir": ("division-con-resto-5", "División con resto"),
        "divisibilidad_5": ("multiplos-y-divisores", "Múltiplos y divisores"),
        "equivalencias_medida": ("equivalencias-de-medida-5", "Equivalencias de medida"),
        "estructura_textos_5": ("el-instructivo", "Instrucciones que sí se pueden seguir"),
        "fracciones_avanzado": ("fracciones-equivalentes-2", "Fracciones equivalentes (II)"),
        "geometria_5": ("aristas-de-un-cuerpo", "Aristas y vértices"),
        "graficos_5": ("tablas-y-graficos", "Tablas y gráficos"),
        "homofonos_5": ("be-y-ve", "B larga y V corta"),
        "pago_exacto": ("pago-exacto", "Pagar con billetes"),
        "perimetro_area_5": ("perimetro-y-area", "Perímetro y área"),
        "problemas_pasos_5": ("problemas-de-varios-pasos", "Problemas de varios pasos"),
        "proporcionalidad_5": ("proporcionalidad-directa", "Proporcionalidad directa"),
        "reconstruir_entero_5": ("reconstruir-la-unidad", "Reconstruir la unidad"),
        "recta_millon_5": ("el-rango-del-millon", "El rango del millón"),
        "recta_numerica": ("recta-hasta-el-millon", "La recta hasta el millón"),
        "romanos_5": ("numeros-romanos", "Números romanos"),
        "sujeto_predicado": ("sujeto-tacito", "El sujeto que no está escrito"),
        "suma_fracciones": ("suma-de-fracciones", "Suma de fracciones"),
        "transportador": ("medir-angulos", "Medir ángulos"),
        "verbos_pasado": ("pasados", "Los dos pasados"),
    },
    6: {
        "area_fraccionaria_6": ("multiplicar-fracciones", "Multiplicar fracciones"),
        "area_perimetro_6": ("area-y-perimetro-6", "Área y perímetro"),
        "cohesion_6": ("escribir-sin-repetir", "Escribir sin repetir"),
        "conjugacion_6": ("modos-del-verbo", "Los modos del verbo"),
        "corredor_coma_6": ("multiplicar-y-dividir-por-ceros", "Multiplicar y dividir por 10, 100 y 1.000"),
        "cuadrilateros_6": ("clasificar-cuadrilateros", "Clasificar cuadriláteros"),
        "densidad_recta_6": ("densidad-en-la-recta", "La recta con saltos chicos"),
        "desarrollos_6": ("cuerpos-y-desarrollos", "Cuerpos y sus desarrollos"),
        "descuentos_6": ("descuentos-y-aumentos", "Descuentos y aumentos"),
        "divisibilidad_criterios_6": ("criterios-de-divisibilidad", "Criterios de divisibilidad"),
        "fraccion_cantidad_6": ("fraccion-de-una-cantidad-6", "Fracción de una cantidad"),
        "fraccion_inversa_6": ("fraccion-inversa", "La fracción inversa"),
        "fracciones_equivalentes_6": ("fracciones-equivalentes-6", "Fracciones equivalentes"),
        "hechos_opiniones": ("hechos-y-opiniones", "Hechos y opiniones"),
        "idea_principal_6": ("la-idea-principal", "De qué se trata, en una sola frase"),
        "jerarquia_6": ("jerarquia-de-operaciones", "Jerarquía de las operaciones"),
        "moda_encuesta_6": ("frecuencias-y-graficos", "Frecuencias y gráficos"),
        "multiplicar_coma_6": ("multiplicar-y-dividir-decimales", "Multiplicar y dividir decimales"),
        "numeros_gigantes_6": ("valor-posicional-millones", "Valor posicional hasta los millones"),
        "od_oi_6": ("objetos-del-verbo", "Objeto directo e indirecto"),
        "permutaciones_6": ("permutaciones-y-combinaciones", "Combinaciones"),
        "poligonos_lados": ("poligonos-y-sus-lados", "Polígonos"),
        "porcentaje_cantidad_6": ("porcentaje-de-una-cantidad", "Porcentajes"),
        "primos_6": ("numeros-primos", "Números primos"),
        "probabilidad_6": ("probabilidad-de-sucesos", "Probabilidad de sucesos"),
        "problemas_varios_pasos_6": ("problemas-de-varios-pasos-6", "Problemas de varios pasos"),
        "proporcionalidad_6": ("proporcionalidad-6", "Proporcionalidad directa"),
        "puntuacion_6": ("donde-abre-la-pregunta", "Dónde se abre la pregunta"),
        "reconstruir_division_6": ("partes-de-la-division-6", "Las partes de la división"),
        "sintagma_6": ("circunstanciales", "Dónde, cuándo y cómo"),
        "suma_angulos": ("suma-de-angulos", "La suma de los ángulos"),
        "suma_fracciones_6": ("suma-y-resta-de-fracciones", "Sumar y restar fracciones"),
        "tildes_6": ("tilde-en-el-hiato", "La tilde que rompe el diptongo"),
    },
    7: {
        "analisis_sintactico_7": ("oracion-compuesta", "Una oración o dos pegadas"),
        "areas_7": ("areas-de-figuras", "Áreas de figuras"),
        "cazador_errores": ("cazador-de-errores", "Cazador de errores"),
        "decimales_periodo_7": ("operaciones-con-decimales", "Operaciones con decimales"),
        "densidad_7": ("numeros-en-la-recta", "Números en la recta"),
        "divisibilidad_7": ("multiplos-divisores-y-criterios", "Múltiplos, divisores y criterios"),
        "ecuaciones_simples": ("ecuaciones-de-primer-grado", "Ecuaciones de primer grado"),
        "expresion_objetivo_7": ("operaciones-combinadas", "Operaciones combinadas"),
        "homofonos": ("homofonos", "Homófonos"),
        "ingles_basico": ("ingles-basico", "Inglés básico"),
        "mcm_dcm_7": ("multiplo-comun-menor", "Múltiplo común menor"),
        "media_mediana_moda_7": ("media-y-mediana", "Media y mediana"),
        "multiplicar_fracciones_7": ("operaciones-con-fracciones", "Operaciones con fracciones"),
        "numeracion_7": ("sistema-de-numeracion", "El sistema de numeración"),
        "ortografia_7": ("los-porques", "Los cuatro porqués"),
        "persuasion_7": ("para-que-esta-escrito", "Para qué está escrito"),
        "potencias_7": ("potencias", "Potencias"),
        "probabilidad_arbol_7": ("probabilidad-7", "Probabilidad"),
        "problemas_pasos_7": ("problemas-de-varios-pasos-7", "Problemas de varios pasos"),
        "proporcionalidad": ("proporcionalidad-directa-e-inversa", "Proporcionalidad directa e inversa"),
        "proporcionalidad_grafico_7": ("graficos-y-tablas", "Gráficos y tablas"),
        "proporcionalidad_inversa_7": ("division-de-fracciones", "División de fracciones"),
        "razon_porcentaje_7": ("razones-y-proporciones", "Razones y proporciones"),
        "recursos_argumentador_7": ("armar-un-argumento", "Armar un argumento"),
        "traductor_algebraico_7": ("lenguaje-algebraico", "Lenguaje algebraico"),
    },
}


def de(grado, actividad):
    """El tema de la seño para esa tarjeta en ese grado, o None."""
    return (CLASES.get(grado) or {}).get(actividad)
